Remove Gemfile.lock
  Run bundle update --bundler
  Fetching gem metadata from https://rubygems.org/.
  An update to the version of bundler itself was requested, but the lockfile can't
  be updated because frozen mode is set

  Run `bundle install` elsewhere and add the updated Gemfile.lock to version
  control.
  If this is a development machine, remove the Gemfile freeze by running `bundle
  config set frozen false`.
  Error: Process completed with exit code 16.